baseURL = "https://ehipassa.org/"
languageCode = "zh-hans"
title = "往見"

[permalinks]
    dhp = "/:filename/"
    patimokkha = "/:filename/"
    majjhima = "/:filename/"
    maoshi = "/:filename/"
    vm = "/:filename/"
