baseURL = "https://ehipassa.org/"
title = "往見"

hasCJKLanguage = true
languageCode = "zh"

disableKinds = ["taxonomy", "term"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
