baseURL = "https://ehipassa.org/"
title = "往見"

hasCJKLanguage = true
languageCode = "zh"

disableKinds = ["taxonomy", "term"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = false
        noClasses = false
        style = "dracula"
        tabWidth = 2
